name: petct
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - black=19.10b0
  - matplotlib=3.5.2
  - numpy=1.22.1
  - pandas=1.4.2
  - pip=21.2.4
  - pylint=2.12.2
  - pytest=7.1.1
  - python=3.9.0
  - pytorch=1.11.0
  - torchvision=0.12.0
  - psutil=5.8.0
  - cudatoolkit
  - pip:
    - monai-weekly==0.9.dev2222
    - monailabel-weekly==0.4.dev2222
    - GeodisTK
    - scikit-image==0.19.2
    - pydicom==2.2.2
    - itk==5.2.1.post1
    - SimpleCRF
    - dash
